# Generated by Django 2.1.5 on 2019-03-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0002_auto_20190314_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
