# Generated by Django 2.1.5 on 2019-03-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0003_auto_20190314_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunit',
            name='property_tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.Property'),
        ),
    ]
