# Generated by Django 2.1.5 on 2019-03-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0004_auto_20190314_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='tenant',
            new_name='user',
        ),
    ]
