# Generated by Django 2.1.5 on 2019-03-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0005_auto_20190315_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='as_from',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
