# Generated by Django 2.1.5 on 2019-03-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0006_auto_20190315_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='has_vacated',
            field=models.BooleanField(default=False),
        ),
    ]
