# Generated by Django 2.1.5 on 2019-03-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0007_tenant_has_vacated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalunit',
            name='property_tag',
        ),
        migrations.AddField(
            model_name='rentalunit',
            name='property_tag',
            field=models.ManyToManyField(related_name='property_tag', to='rentalApp.Property'),
        ),
    ]
