# Generated by Django 2.1.5 on 2019-03-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0009_auto_20190315_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='profile_photo',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile/'),
        ),
    ]
